### ISSUE TITLE
BotFrameworkAdapter does not work correctly with Azure Functions 2.x

### ISSUE THREAD

**Issue by iMicknl** [Microsoft/botbuilder-js#400]
While using BotBuilder v4 SDK in combination with Azure Functions I found out that the log is full of errors, because of multiple calls to the .done() function. As far as I could test, the functionality isn't impacted. Version 3 had a special ChatConnector for use with Azure Functions.

```Error: 'done' has already been called. Please check your script for extraneous calls to 'done'.```
[Gist with example code](https://gist.github.com/iMicknl/1ea361b153d0c798766597e8e593b683)

Is this something that is on the radar already? I couldn't find any information about it yet. Any guidance regarding using the BotBuilder v4 SDK with serverless offerings would be nice.

**Comment by tomlm** [comment]
I've not tried it but you should await the call to processactivity.

await adapter.processActivity( … );
done();

**Comment by iMicknl** [comment]
Are you sure? In all examples I checked in this repository, `adapter.processActivity()` isn't an async call. However I just checked it and I can still reproduce `Error: 'done' has already been called. Please check your script for extraneous calls to 'done'.`

It would be great if there would be guidance for running a BotBuilder V4 bot on Azure Functions when it will be GA.

**Comment by iMicknl** [comment]
>Bot Framework SDK v4 is now available and comes with many updates and new functionality. Function Bots are based on SDK v3, we recommend you create a Web App Bot instead, which supports the new SDK v4.

Quote from the Azure Portal. Does this mean that we don't support Azure Functions for the Bot Builder SDK at all?

**Comment by EricDahlvang** [comment]
@iMicknl Have you tried awaiting the method as Tom suggests?  and calling .Done() from within adapter.processActivity()?  Something like:

```js
module.exports = async function (func, req) {

    await adapter.processActivity(req, func.res, async (context) => {
        
	//process the activity here
		
		
        func.done();
    });
};
```

**Comment by iMicknl** [comment]
@EricDahlvang, yes I already tried it as stated in my last comment. However, will give it another try this week.

There is no documentation on docs.Microsoft about Azure Functions in combination with the Bot Framework. Is using serverless for bots something we don't encourage anymore?

**Comment by sgellock** [comment]
For single turn conversations using functions to implement this conversation pattern is a reasonable approach.  Outside of that, we don't suggest using functions for multi-turn dialog conversations.  Additionally, the team does not have any additional functions work planned on our immediate roadmap.

**Comment by sjoerdkoolen** [comment]
Silly question.. what's a multi turn dialog?

**Comment by sgellock** [comment]
It’s a term used to describe a type of conversation flow.  It’s when the bot has a requirement to get data from the user that requires processing more than one turn.

e.g.
Bot says:  What is your name?
User says:  Scott
Bot Says:  Hello Scott.  Where do you live?
User says:  Seattle.
